### ISSUE TITLE
Static analyzer for standard an ultra circuits

### ISSUE THREAD

**Issue by Rumata888** [AztecProtocol/barretenberg#1086]
A mechanism that treats the whole circuit before finalization (in case of ultra) as a graph with additional information and looks at the following properties:
1) How many independent subgraphs (real variables being vertices) there are
2) Whether there are any unexpected variables only present in 1 gate (apart from known cases this signals and underconstrained circuit)
```[tasklist]
### Tasks
- [x] Create Initial implementation of static analyzer with lookup, arithmetic, sorted, elliptic gates taken care of
- [x] Create PR patch for the discovered issue
- [x] Finalize and clean up PR with initial implementation and with AES and SHA256 tests
- [x] Create tests for blake
- [x] Extend mechanism to Auxiliary and Poseidon gates
- [x] Create tests for cycle group
```

**Comment by Rumata888** [comment]
https://github.com/AztecProtocol/aztec-packages/pull/12130
