### ISSUE TITLE
Epic: In-browser bb.js MVP

### ISSUE THREAD

**Issue by Savio-Sou** [AztecProtocol/barretenberg#517]
As a Noir developer / bb.js user, I want to generate proofs in Next.js using bb.js, so I can later verify them e.g. on-chain.

```[tasklist]
### First priorities
- [ ] https://github.com/AztecProtocol/barretenberg/issues/607
- [x] Fix `test/bin-test.sh` -> currently broken due to `dynamic/...` paths
```

```[tasklist]
### Second priorities
- [x] Make GitHub workflow output artifacts to AztecProtocol/bb.js
- [ ] Re-enable strict mode on tsconfig
```

**Comment by jonybur** [comment]
https://github.com/orgs/noir-lang/projects/1/views/13?pane=issue&itemId=31105281
https://github.com/orgs/noir-lang/projects/1/views/13?pane=issue&itemId=31105314

**Comment by jonybur** [comment]
https://github.com/orgs/noir-lang/projects/1/views/13?pane=issue&itemId=31215139

**Comment by Savio-Sou** [comment]
@jonybur are the issues all resolved?

**Comment by jonybur** [comment]
@Savio-Sou Just updated the list with TODOs. Currently waiting on a review to see if the solution that the PR is proposing is OK.

**Comment by Savio-Sou** [comment]
Thanks @jonybur 🙌

Just to clarify are they essential to proving in Next.js with bb.js, or more like extra upgrades / best practices on top?

**Comment by Savio-Sou** [comment]
@jonybur is this wrapped / up-to-date?

**Comment by jonybur** [comment]
@Savio-Sou This is up to date. The two remaining things, outputting to AztecProtocol/bb.js and enabling strict are optional but we should still track them

**Comment by Savio-Sou** [comment]
Thanks Jony 🙌 sounds like we have an MVP in that case?

Should we close this and track the two issues on another Epic (e.g. "Enhance bb.js DevEx", not sure what makes sense)?

**Comment by jonybur** [comment]
Yes this is already working and in production so I'd consider it to be at an MVP level. I'd move those two tickets to a backlog for further improvements.
