### ISSUE TITLE
Cleanup release-please workflow

### ISSUE THREAD

**Issue by kevaundray** [AztecProtocol/barretenberg#601]
The following are tasks that need to be done to clean-up the release-please workflow:

- [x] Remove the alpha tag from typescript releases (#602)
- [x]  Use a conventional naming scheme for binaries being released (https://github.com/AztecProtocol/aztec-packages/pull/1837)
- [x] Tar and Gzip the .wasm file (#604)
- [x] Install WASI SDK as a separate step instead of in the `Run Bootstrap test` (#604)
- [x] Only build wasm version once when compiling typescript (#604)
- [x] Target older ubuntu. Currently we target ubuntu-latest which is ubuntu-22 (#609)

**Comment by kevaundray** [comment]
The above list was generated from Charlies offline review.

Need to investigate if we need to save two WASM binaries: the one that we generate using the `wasm-threads` preset and the one we generate using the `wasm` preset.
