### ISSUE TITLE
Handle the points at infinity (∞)

### ISSUE THREAD

**Issue by codygunton** [AztecProtocol/barretenberg#911]
This is a tracking issue for our various issues relating to the point at infinity.

```[tasklist]
### Tasks
- [ ] https://github.com/AztecProtocol/barretenberg/issues/866
- [ ] https://github.com/AztecProtocol/barretenberg/issues/905
- [ ] https://github.com/AztecProtocol/barretenberg/issues/871
- [ ] https://github.com/AztecProtocol/aztec-packages/issues/2214
- [ ] https://github.com/AztecProtocol/barretenberg/issues/1100
```

**Comment by codygunton** [comment]
Closed by https://github.com/AztecProtocol/aztec-packages/pull/4751 unclosed by https://github.com/AztecProtocol/aztec-packages/pull/5174 and then closed again by https://github.com/AztecProtocol/aztec-packages/pull/5189

**Comment by codygunton** [comment]
Whoops

**Comment by ledwards2225** [comment]
Letting the standalone issues stand on their own
